import Head from "next/head";
import styles from "../styles/home.module.css";
import Image from "next/image";

import HeroImg from "../../public/assets/hero.png";

export default function Home() {
   return (
      <div className={styles.container}>
         <Head>
            <title>App tarefas+ | Organize suas tarefas de forma fácil</title>
            <meta name="description" content="Generated by create next app" />
            <meta
               name="viewport"
               content="width=device-width, initial-scale=1"
            />
         </Head>
         <main className={styles.logo}>
            <div className={styles.logoContent}>
               <Image
                  className={styles.hero}
                  alt="Logo Tarefas"
                  src={HeroImg}
               />
            </div>
            <h1 className={styles.title}>
               Sistema feito para você organizar <br />
               seus estudos e tarefas
            </h1>
            <div className={styles.infoContent}>
               <section className={styles.box}>
                  <span>+12 posts</span>
               </section>
               <section className={styles.box}>
                  <span>+90 comentarios</span>
               </section>
            </div>
         </main>
      </div>
   );
}
