import Head from "next/head";
import styles from "../styles/home.module.css";
import Image from "next/image";

import HeroImg from "../../public/assets/hero.png";
import { GetStaticProps } from "next";
import { collection, getDocs } from "firebase/firestore";
import { db } from "../services/firebaseConnection";

interface HomeProps {
   posts: number;
   comments: number;
}

export default function Home({ posts, comments }: HomeProps) {
   return (
      <div className={styles.container}>
         <Head>
            <title>App tarefas+ | Organize suas tarefas de forma fácil</title>
            <meta name="description" content="Generated by create next app" />
            <meta
               name="viewport"
               content="width=device-width, initial-scale=1"
            />
         </Head>
         <main className={styles.logo}>
            <div className={styles.logoContent}>
               <Image
                  className={styles.hero}
                  alt="Logo Tarefas"
                  src={HeroImg}
               />
            </div>
            <h1 className={styles.title}>
               Sistema feito para você organizar <br />
               seus estudos e tarefas
            </h1>
            <div className={styles.infoContent}>
               <section className={styles.box}>
                  <span>+{posts} posts</span>
               </section>
               <section className={styles.box}>
                  <span>+{comments} comentarios</span>
               </section>
            </div>
         </main>
      </div>
   );
}

export const getStaticProps: GetStaticProps = async () => {
   // Buscar do banco os numeros e mandr pro components
   const commentRef = collection(db, "comments");
   const postRef = collection(db, "tarefas");

   const commentSnapshot = await getDocs(commentRef);
   const postSnapshot = await getDocs(postRef);

   return {
      props: {
         posts: postSnapshot.size || 0,
         comments: commentSnapshot.size || 0,
      },
      revalidate: 90, // revalidada a cada 90 segundos
   };
};
